version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb_custom
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
      MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
    secrets:
      - db_password.txt
      - db_root_password.txt
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress_custom
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    expose:
      - "9000"
    secrets:
      - db_password.txt
      - wp_admin_password.txt
      - wp_user_password.txt

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx_custom
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

secrets:
  db_root_password.txt:
    file: ../secrets/db_root_password.txt
  db_password.txt:
    file: ../secrets/db_password.txt
  wp_admin_password.txt:
    file: ../secrets/wp_admin_password.txt
  wp_user_password.txt:
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    driver: bridge
